Repository owncloud/files_external_dropbox, pull requests merged in 2020-04, with the labels that each got.

#82 Update league/flysystem 1.0.66 and symfony
  composer.lock
Labels: 3 - To review, dependencies

#83 Bump phan 2.7
  vendor-bin/phan/composer.json
Labels: QA-team

#87 [Tests-Only] Bump phpstan to 0.12
  vendor-bin/phpstan/composer.json
Labels: 3 - To review, QA-team

#88 Adjust drone pipelines php 7.4
  .drone.star
  .gitignore
Labels: 3 - To review, QA-team
